# This single codebase performs generating of subject, verb, article, adjective, and noun, plus sentence assembly.
# True microservices would have separate codebases, but for our purposes a single codebase is fine.
# Run by opening 6 separate command prompts:
# java -jar -Dspring.profiles.active=subject lab-4-eureka-client-solution-1.jar
# java -jar -Dspring.profiles.active=verb lab-4-eureka-client-solution-1.jar
# java -jar -Dspring.profiles.active=article lab-4-eureka-client-solution-1.jar
# java -jar -Dspring.profiles.active=adjective lab-4-eureka-client-solution-1.jar
# java -jar -Dspring.profiles.active=noun lab-4-eureka-client-solution-1.jar
# java -jar -Dspring.profiles.active=sentence lab-4-eureka-client-solution-1.jar

---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8010/eureka/


# TODO-04: Expose the actuator endpoint for Prometheus.
# Add "prometheus" in the management.endpoints.web.exposure.include list.
# Also set the management.metrics.tags.application: to ${spring.application.name}
management:
  endpoints.web.exposure.include: health,info,beans,env,metrics,configprops,mappings,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env.enabled: true
    java.enabled: true
    os.enabled: true
    process.enabled: true
info.active-profiles: ${spring.profiles.active:none}
info.name: ${spring.application.name:none}



server:
  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

# Depending on which profile is active, the application gives 
# itself a different name when registering with Eureka
---
spring:
  config.activate.on-profile: sentence
  application:
    name: lab-4-sentence  
server:
  port: 8020  
words: NotApplicable
    
---
spring:
  config.activate.on-profile: subject
  application:
    name: lab-4-subject  
words: I,You,He,She,It
  
---
spring:
  config.activate.on-profile: verb
  application:
    name: lab-4-verb  
words: ran,knew,had,saw,bought

---
spring:
  config.activate.on-profile: article
  application:
    name: lab-4-article  
words: a,the

---
spring:
  config.activate.on-profile: adjective
  application:
    name: lab-4-adjective  
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  config.activate.on-profile: noun
  application:
    name: lab-4-noun  
words: boat,book,vote,seat,backpack,partition,groundhog
