# Properties active for ALL profiles:
---
spring:
  application:
    name: sentence
  config:
    import: "optional:configserver:http://localhost:8001"    # Where should we call the config server at?

server:
  port: 8020      # Fix the sentence server to 8020.  This makes it easy to find.

# Expose Actuator endpoints.  Allow application to be more useful from Eureka.
management.endpoints.web.exposure.include: health,info,beans,env,configprops,mappings
management.info:
  env.enabled: true
  java.enabled: true
  os.enabled: true
  process.enabled: true
info.active-profiles: ${spring.profiles.active:none}
info.name: ${spring.application.name:none}
