global:
  scrape_interval: 20s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
- job_name: 'spring-applications'
  metrics_path: '/actuator/prometheus'
  scrape_interval: 3s # This can be adjusted based on our needs
  static_configs:
  - targets: ['host.docker.internal:8001']
  - targets: ['host.docker.internal:8002']

