global:
  scrape_interval: 20s
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:

# Make Prometheus scrape itself for metrics.
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

# Discover Eureka services to scrape.
- job_name: 'eureka'

  # Go to Eureka to get a list of discovered services.
  # Use "host.docker.internal" to access the host machine from a Docker container:
  eureka_sd_configs:
  - server: http://host.docker.internal:8010/eureka

  relabel_configs:
  # Tell Prometheus to scrape the /actuator/prometheus endpoints
  - target_label: __metrics_path__
    replacement: /actuator/prometheus  # relabel_configs:

