# This 'name' of our application is important 
# as the config server typically has to serve up properties for many applictions:
spring:
  application:
    name: lab-3-client					# What set of properties will we ask the config server for?

  config:
    import: "optional:configserver:http://localhost:8001"    # Where should we call the config server at?


# Uncomment these lines to activate "northamerica" as the active profile.
# Ordinarily we would not activate a profile from within a property file, but this is just a demo:
  # profiles:
  #   active: northamerica

server:
  port: 8002							# What port should we expose for our web interface

