spring:
  application.name: Lab 3 Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kennyk65/Microservices-With-Spring-Student-Files
          searchPaths: ConfigDataNew
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
          
server:
  port: 8001

# Eliminate logging noise when "main" branch is not found in git repository:
logging.level:
  org.springframework.cloud.config.server:
    environment.MultipleJGitEnvironmentRepository: WARN
