---
spring:
  application:
    name: lab-11-sentence-server

  config:
    import: "optional:configserver:http://localhost:8001"    # Where should we call the config server at?

  # Allow thymeleaf template changes to reload:
  thymeleaf.cache: false

server:
  port: 8088

# The Spring Cloud Gateway uses Netty, which has trouble resolving a windows hostname.
# To resolve this, instruct Eureka to use localhost as the hostname.
eureka:
  instance:
    hostname: localhost

# Expose Actuator endpoints.  Allow application to be more useful from Eureka.
management:
  endpoints.web.exposure.include: health,info,beans,env,configprops,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env.enabled: true
    java.enabled: true
    os.enabled: true
    process.enabled: true
info.active-profiles: ${spring.profiles.active:none}
info.name: ${spring.application.name:none}
