---
# This default profile is used when running a single instance completely standalone:

spring:
  application:
    name: common-eureka-server
server:
  port: 8010  
eureka:
  instance:
    hostname: eurekahost  
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    

# primary, secondary, and tertiary illustrate running 3 intercommunicating instances.  This example has them running
# side-by-side on localhost -- which is unrealistic in production -- but does illustrate how multiple instances collaborate.
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=primary lab-4-eureka-server-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=secondary lab-4-eureka-server-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=tertiary lab-4-eureka-server-solution-0.0.1-SNAPSHOT.jar

---
spring:
  config.activate.on-profile: primary
server:
  port: 8011  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring:
  config.activate.on-profile: secondary
server:
  port: 8012  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8013/eureka/,http://localhost:8011/eureka/

---
spring:
  config.activate.on-profile: tertiary
server:
  port: 8013  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/
      