---
# This default profile is used when running a single instance completely standalone:
spring:
  profiles: default
server:
  port: 8010  
eureka:
  instance:
    hostname: localhost  
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    

# primary, secondary, and tertiary illustrate running 3 intercommunicating instances.  This example has them running
# side-by-side on localhost -- which is unrealistic in production -- but does illustrate how multiple instances collaborate.
# Run by opening 3 separate command prompts:
# java -jar -Dspring.profiles.active=primary lab-4-eureka-server-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=secondary lab-4-eureka-server-solution-0.0.1-SNAPSHOT.jar
# java -jar -Dspring.profiles.active=tertiary lab-4-eureka-server-solution-0.0.1-SNAPSHOT.jar

---
spring:
  profiles: primary
  application:
    name: eureka-server-clustered
server:
  port: 8011  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: eureka-primary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/}

---
spring:
  profiles: secondary
  application:
    name: eureka-server-clustered
server:
  port: 8012  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: eureka-secondary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-tertiary:8013/eureka/,http://eureka-primary:8011/eureka/}

---
spring:
  profiles: tertiary
  application:
    name: eureka-server-clustered
server:
  port: 8013  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    hostname: eureka-tertiary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/}
      