---
spring:
  application.name: Common Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kennyk65/Microservices-With-Spring-Student-Files
          searchPaths: ConfigDataNew
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/

server:
  port: 8001

# Expose the actuator endpoints for Prometheus and a few other things.
# Place useful data in the "info" endpoint.
# Also set the management.metrics.tags.application: to ${spring.application.name} so
# that this application's name appears in Prometheus / Grafana.
management:
  endpoints.web.exposure.include: health,info,beans,env,metrics,configprops,mappings,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env.enabled: true
    java.enabled: true
    os.enabled: true
    process.enabled: true
info.active-profiles: ${spring.profiles.active:none}
info.name: ${spring.application.name:none}


# Eliminate logging noise when "main" branch is not found in git repository:
logging.level:
  org.springframework.cloud.config.server:
    environment.MultipleJGitEnvironmentRepository: WARN

